### ISSUE TITLE
Installation on Windows 11

### ISSUE THREAD

**Issue by iasonasiasonos** [karikolehmainen/RAMP-IoT#6]
I have installed RAMP-IOT on my Windows 11 machine and ot the attached error. Is the RAMP IOT installed correctly? Does this run on Windows 11 or it should be installed on Linux machined only?
![Screenshot 2022-05-31 132044](https://user-images.githubusercontent.com/15981121/171152307-6e7ec70b-7766-4ba6-8a65-7cc0ba9e74b9.png)

**Comment by karikolehmainen** [comment]
Hi, Currently RAMP-IoT is supported only Linux machines. Any Debian based system should be OK but system is tested on with Ubuntu v20 LTS. If you need windows, you can take only the docler-compose.yml file and install that using docker-compose on Windows. It is a bit more involved way of doing things, but FIWARE system should work just fine.

**Comment by karikolehmainen** [comment]
I will close the issue but if you need support for Windows installation, please go ahead and post questions here or open new issue.
